### ISSUE TITLE
[Issue] Unable to install globally

### ISSUE THREAD

**Issue by Aju100** [r3curs1v3-pr0xy/sub404#4]
Hey @r3curs1v3-pr0xy ,

I am not able to install globally sub404 instead of manually workouts like this
```
python3 sub404.py -h
```

I wanted to use it globally like this one.
```
sub404
```

### Steps to reproduce the issue
```
    git clone https://github.com/r3curs1v3-pr0xy/sub404.git
    pip3 install -r sub404/requirements.txt
    sudo chmod +x sub404/sub404.py
    sudo cp sub404/sub404.py /usr/bin/sub404
```

### Errors
```
import: unable to grab mouse '': No such file or directory @ error/xwindow.c/XSelectWindow/9301.
import: unable to read X window image '': Success @ error/xwindow.c/XImportImage/4933.
import: unable to read X window image '': Success @ error/xwindow.c/XImportImage/5040.
import:  `subprocess' @ error/import.c/ImportImageCommand/1288.
/usr/bin/sub404: line 6: syntax error near unexpected token `'win''
/usr/bin/sub404: line 6: `if sys.platform.startswith('win'):'

```

**Comment by r3curs1v3-pr0xy** [comment]
Hi Aju

You can do this by adding a **shebang** at the beginning of sub404.py file. Edit sub404.py and at this line at the top

**#!/bin/python3**

After this, run this command:
 1. sudo chmod +x sub404/sub404.py
 2. sudo cp sub404/sub404.py /usr/bin/sub404

After this you can use this tool just by typing sub404.

**Comment by Aju100** [comment]
Hi @r3curs1v3-pr0xy 

Thank you now it's working by your given code,

```
#!/usr/bin/python
```

**Comment by r3curs1v3-pr0xy** [comment]
Merged

**Comment by Aju100** [comment]
Thank you @r3curs1v3-pr0xy .
